# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Apprendre
subtitle: Version du 1 décembre 2021
author: Groupe de travail DGEP, EPFL, HEP Vaud, UNIL
logo: logo_modulo.svg
exclude_patterns: ['**/maitre.md', 'content/ens/**', '**/old_**']

#######################################################################################
# Execution settings
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: false
  #execute_notebooks           : cache

#######################################################################################
# Define the latex engine and the name of the latex output file for PDF builds
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: eleve.tex

#######################################################################################
sphinx:
  config:
    user_role: eleve
    glossary_doc: content/glossaire
    html_show_copyright: false
    language: fr
    html_theme: sphinx_book_theme
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    html_favicon: favicon.ico
    html_extra_path: ['../assets']
    html_theme_options:
      search_bar_text: "Rechercher…"
      use_download_button: true
      repository_url: https://github.com/edunumsec2/book
      use_issues_button: true
      use_repository_button: true
      use_edit_page_button: false
      extra_navbar: ""
      extra_footer: |
        <p>
        <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">
        <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" />
        </a>
        <br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">
        Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License
        </a>.
        </p>
    myst_enable_extensions:
      - amsmath
      - colon_fence
      - deflist
      - dollarmath
      - html_admonition
      - html_image
      - linkify
      - replacements
      - smartquotes
      - substitution
  local_extensions:
    questions: ../extensions/
    blanks: ../extensions/
    videos: ../extensions/
    codeplay: ../extensions/
    logic: ../extensions/
    role: ../extensions/
    glossary: ../extensions/
    timeline: ../extensions/

#######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Information about where the book exists on the web
repository:
  url: https://github.com/edunumsec2/book  # Online location of your book
  path_to_book: content  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface: "classic" # or "jupyterlab"
# Possibilité de connecter un kernel du projet Noto de l'EPFL
## jupyterhub_url: "https://noto.epfl.ch/user/ch-epfl-identifiantdelutilisateur"

#######################################################################################
#binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"
