# Table of content

format: jb-book
## Page d'accueil
root: content/appr/accueil

parts:
## Première année
- caption: Première année
  numbered: false
  chapters:
  ### Représentation de l'information
  - file: content/appr/theme/rep-info/accueil/eleve
    sections:
      - file: content/appr/theme/rep-info/cours/intro/eleve
      - file: content/appr/theme/rep-info/cours/entiers/eleve
      - file: content/appr/theme/rep-info/cours/caracteres/eleve
      - file: content/appr/theme/rep-info/cours/images/eleve
      - file: content/appr/theme/rep-info/cours/son/eleve
      - file: content/appr/theme/rep-info/cours/redondance/eleve
      - file: content/appr/theme/rep-info/cours/conclusion/eleve

  ### Programmation    
#  - file: content/appr/theme/prog1/accueil/elevenew
  - file: content/appr/theme/prog1/new/intro

    sections:
#      - file: content/appr/theme/prog1/cours/1_intro/intro 
#      - file: content/appr/theme/prog1/cours/2_pyth/pyth
#      - file: content/appr/theme/prog1/cours/3_var/var
#      - file: content/appr/theme/prog1/cours/4_flux/flux
#      - file: content/appr/theme/prog1/cours/5_list/list
#      - file: content/appr/theme/prog1/cours/6_dict/dict
#      - file: content/appr/theme/prog1/cours/7_fonc/fonc
#      - file: content/appr/theme/prog1/cours/8_mod/mod

      - file: content/appr/theme/prog1/new/dessiner
      - file: content/appr/theme/prog1/new/colorier
      - file: content/appr/theme/prog1/new/repeter
      - file: content/appr/theme/prog1/new/cercler
      - file: content/appr/theme/prog1/new/parcourir
      - file: content/appr/theme/prog1/new/repondre
      - file: content/appr/theme/prog1/new/ecrire
      - file: content/appr/theme/prog1/new/calculer
      - file: content/appr/theme/prog1/new/iterer
      - file: content/appr/theme/prog1/new/attendre
      - file: content/appr/theme/prog1/new/decider
      - file: content/appr/theme/prog1/new/definir
      - file: content/appr/theme/prog1/new/renvoyer
      - file: content/appr/theme/prog1/new/grouper 
      - file: content/appr/theme/prog1/new/randomiser
      - file: content/appr/theme/prog1/new/trier
      - file: content/appr/theme/prog1/new/turtleart
      
#     - file: content/appr/theme/prog1/cours/9_app/app 
#     - file: content/appr/theme/prog1/cours/10_conclusion/concl 

  ### Algorithmique         
  - file: content/appr/theme/algo1/accueil/eleve
    sections:
      - file: content/appr/theme/algo1/cours/0_intro/eleve
      - file: content/appr/theme/algo1/cours/1_les_algorithmes/eleve
      - file: content/appr/theme/algo1/cours/2_trie_cherche_trouve/eleve
      - file: content/appr/theme/algo1/cours/3_des_algos_aux_prog/eleve
      - file: content/appr/theme/algo1/cours/4_conclusion/eleve

  ### Architecture des ordinateurs    
  - file: content/appr/theme/archi/accueil/eleve
    sections:
      - file: content/appr/theme/archi/cours/0_intro/eleve
      - file: content/appr/theme/archi/cours/1_syst_logiques/eleve
      - file: content/appr/theme/archi/cours/2_additionneur/eleve
      - file: content/appr/theme/archi/cours/3_alu_et_memoire/eleve
      - file: content/appr/theme/archi/cours/4_archi_gen_comp/eleve
      - file: content/appr/theme/archi/cours/5_micropro/eleve
      - file: content/appr/theme/archi/cours/6_conclusion/eleve
      

- caption: Deuxième année
  numbered: false
  chapters:
  - file: content/appr/theme/algo2/0_landing
    sections:
      - file: content/appr/theme/algo2/cours/introduction/eleve
      - file: content/appr/theme/algo2/cours/terminaison/eleve
      - file: content/appr/theme/algo2/cours/complexite/eleve
      - file: content/appr/theme/algo2/cours/heuristiques/eleve
      - file: content/appr/theme/algo2/cours/recursivite/eleve
      - file: content/appr/theme/algo2/cours/conclusion/eleve
  - file: content/appr/theme/prog2/intro
    sections:
      - file: content/appr/theme/prog2/onkey    
      - file: content/appr/theme/prog2/turtle
      - file: content/appr/theme/prog2/class
      - file: content/appr/theme/prog2/dict
      - file: content/appr/theme/prog2/compter
      - file: content/appr/theme/prog2/math
      - file: content/appr/theme/prog2/color
      - file: content/appr/theme/prog2/tuple
      - file: content/appr/theme/prog2/ensemble
      - file: content/appr/theme/prog2/logique
      - file: content/appr/theme/prog2/bitwise
      - file: content/appr/theme/prog2/recursif

      - file: content/appr/theme/prog2/onclick
      - file: content/appr/theme/prog2/idees
      - file: content/appr/theme/prog2/quiz
      
  - file: content/appr/theme/projets/intro
    sections:
      - file: content/appr/theme/projets/tic_tac_toe
      - file: content/appr/theme/projets/puissance4
      - file: content/appr/theme/projets/snake
      - file: content/appr/theme/projets/game_of_life
      - file: content/appr/theme/projets/cartes
      - file: content/appr/theme/projets/art_absurde
      - file: content/appr/theme/projets/microbit/microbit

  - file: content/appr/theme/reseaux/eleve

- caption: Glossaire
  numbered: false
  chapters:
  - file: content/glossaire

## Annexes
#- caption: Annexes
#  numbered: false
#  chapters:
#  - file: content/appr/annex/accueil
#    sections:
#    - file: content/appr/annex/references/liens
#  - file: content/appr/annex/prolongements/introduction
#    sections:
#    - file: content/appr/annex/prolongements/bioinf/bioinf



