# Table of content

format: jb-book
## Page d'accueil
root: content/appr/accueil

parts:
## Première année
- caption: Première année
  numbered: false
  chapters:
  ### Représentation de l'information
  - file: content/appr/theme/rep-info/accueil/eleve
    sections:
      - file: content/appr/theme/rep-info/cours/intro/eleve
      - file: content/appr/theme/rep-info/cours/entiers/eleve
      - file: content/appr/theme/rep-info/cours/caracteres/eleve
      - file: content/appr/theme/rep-info/cours/images/eleve
      - file: content/appr/theme/rep-info/cours/son/eleve
      - file: content/appr/theme/rep-info/cours/redondance/eleve
      - file: content/appr/theme/rep-info/cours/conclusion/eleve

  ### Programmation    
  - file: content/appr/theme/prog1/intro
    sections:
      - file: content/appr/theme/prog1/dessiner
      - file: content/appr/theme/prog1/definir
      - file: content/appr/theme/prog1/colorier
      - file: content/appr/theme/prog1/repeter
      - file: content/appr/theme/prog1/cercler
      - file: content/appr/theme/prog1/parcourir
      - file: content/appr/theme/prog1/questionner
      - file: content/appr/theme/prog1/calculer
      - file: content/appr/theme/prog1/decider
      - file: content/appr/theme/prog1/ecrire
      - file: content/appr/theme/prog1/write
      - file: content/appr/theme/prog1/iterer
      - file: content/appr/theme/prog1/attendre
      - file: content/appr/theme/prog1/parametrer
      - file: content/appr/theme/prog1/renvoyer
      - file: content/appr/theme/prog1/grouper 
      - file: content/appr/theme/prog1/randomiser
      - file: content/appr/theme/prog1/trier
      - file: content/appr/theme/prog1/turtleart
      - file: content/appr/theme/prog1/projet
      - file: content/appr/theme/prog1/annexe
      
  ### Algorithmique         
  - file: content/appr/theme/algo1/accueil/eleve
    sections:
      - file: content/appr/theme/algo1/cours/0_intro/eleve
      - file: content/appr/theme/algo1/cours/1_les_algorithmes/eleve
      - file: content/appr/theme/algo1/cours/2_trie_cherche_trouve/eleve
      - file: content/appr/theme/algo1/cours/3_des_algos_aux_prog/eleve
      - file: content/appr/theme/algo1/cours/4_conclusion/eleve

  ### Architecture des ordinateurs    
  - file: content/appr/theme/archi/accueil/eleve
    sections:
      - file: content/appr/theme/archi/cours/0_intro/eleve
      - file: content/appr/theme/archi/cours/1_syst_logiques/eleve
      - file: content/appr/theme/archi/cours/2_additionneur/eleve
      - file: content/appr/theme/archi/cours/3_alu_et_memoire/eleve
      - file: content/appr/theme/archi/cours/4_archi_gen_comp/eleve
      - file: content/appr/theme/archi/cours/5_micropro/eleve
      - file: content/appr/theme/archi/cours/6_conclusion/eleve



  ### Histoire de l'informatique  
  - file: content/appr/theme/hist/eleve
    sections:
      - file: content/appr/theme/hist/main1

- caption: Deuxième année
  numbered: false
  chapters:
  - file: content/appr/theme/algo2/landing
    sections:
      - file: content/appr/theme/algo2/intro
      - file: content/appr/theme/algo2/principes
      - file: content/appr/theme/algo2/recherche
      - file: content/appr/theme/algo2/tris
      - file: content/appr/theme/algo2/recursivite
      - file: content/appr/theme/algo2/cours/heuristiques/eleve
      - file: content/appr/theme/algo2/cours/recursivite/eleve
      - file: content/appr/theme/algo2/cours/conclusion/eleve
  - file: content/appr/theme/prog2/intro
    sections:
      - file: content/appr/theme/prog2/onkey
      - file: content/appr/theme/prog2/lambda
      - file: content/appr/theme/prog2/onclick
      - file: content/appr/theme/prog2/ontimer
      - file: content/appr/theme/prog2/turtle
      - file: content/appr/theme/prog2/class
      - file: content/appr/theme/prog2/inherit
      - file: content/appr/theme/prog2/math
      - file: content/appr/theme/prog2/dict
      - file: content/appr/theme/prog2/compter
      - file: content/appr/theme/prog2/color
      - file: content/appr/theme/prog2/set
      - file: content/appr/theme/prog2/bool
      - file: content/appr/theme/prog2/bit
      - file: content/appr/theme/prog2/recursif
      - file: content/appr/theme/prog2/vector
      - file: content/appr/theme/prog2/force
      - file: content/appr/theme/prog2/idees
      
  - file: content/appr/theme/projets/intro
    sections:
      - file: content/appr/theme/projets/tic_tac_toe
      - file: content/appr/theme/projets/puissance4
      - file: content/appr/theme/projets/mines
      - file: content/appr/theme/projets/snake
      - file: content/appr/theme/projets/game_of_life
      - file: content/appr/theme/projets/cartes
      - file: content/appr/theme/projets/tetris
      - file: content/appr/theme/projets/art_absurde
      - file: content/appr/theme/projets/microbit/microbit
      - file: content/appr/theme/projets/crypto
      - file: content/appr/theme/projets/idees

  - file: content/appr/theme/reseaux/eleve

- caption: Glossaire
  numbered: false
  chapters:
  - file: content/glossaire

## Annexes
#- caption: Annexes
#  numbered: false
#  chapters:
#  - file: content/appr/annex/accueil
#    sections:
#    - file: content/appr/annex/references/liens
#  - file: content/appr/annex/prolongements/introduction
#    sections:
#    - file: content/appr/annex/prolongements/bioinf/bioinf



