# Table of content
format: jb-book
root: content/ens/readme/README_pilote
parts:
- caption: Première année
  numbered: false
  chapters: 
  - file: content/ens/theme/rep-info/intro
    sections:
      - file: content/ens/theme/rep-info/activ/presentation
        sections:
          - file: content/ens/theme/rep-info/activ/entiers/magie-binaire/magie_binaire
          - file: content/ens/theme/rep-info/activ/images/EncoderImages/EncoderImages
          - file: content/ens/theme/rep-info/activ/son/echantillonnage
          - file: content/ens/theme/rep-info/activ/redondance/hamming
          - file: content/ens/theme/rep-info/activ/compression/huffman
      - file: content/ens/theme/rep-info/exo/presentation
        sections:
          - file: content/ens/theme/rep-info/exo/caracteres/carte-perforee/exercice
          - file: content/ens/theme/rep-info/exo/redondance/radiotelephonie/exercice
          - file: content/ens/theme/rep-info/exo/images/bitmap/exercice
          - file: content/ens/theme/rep-info/exo/images/tableur/exercice    
      - file: content/ens/theme/rep-info/support/presentation
        sections:
          - file: content/ens/theme/rep-info/support/son/visu-et-ecoute-son
          - file: content/ens/theme/rep-info/support/reels/reels
          - file: content/ens/theme/rep-info/support/redondance/shannon2    

  - file: content/ens/theme/prog1/maitre
    sections:
      - file: content/ens/theme/prog1/cours/1_intro/intro
      - file: content/ens/theme/prog1/activ/microbit/catch-the-fruit/catchFruit 
      - file: content/ens/theme/prog1/activ/microbit-python/intro
        sections:
        - file: content/ens/theme/prog1/activ/microbit-python/affichage
        - file: content/ens/theme/prog1/activ/microbit-python/condition
        - file: content/ens/theme/prog1/activ/microbit-python/variables
  - file: content/ens/theme/algo1/maitre
    sections:
  #  - file: content/ens/theme/algo1/decomposition-probleme/maitre
  #  - file: content/ens/theme/algo1/algorithmes-classiques/maitre
      - file: content/ens/theme/algo1/accueil/solutions
      - file: content/ens/theme/algo1/activ/algorithmes-classiques/algo-tri/algo-tri
      - file: content/ens/theme/algo1/activ/algorithmes-classiques/epidemie/epidemie
        sections:
        - file: content/ens/theme/algo1/activ/algorithmes-classiques/epidemie/fiche
        - file: content/ens/theme/algo1/activ/algorithmes-classiques/epidemie/solution
      - file: content/ens/theme/algo1/activ/algorithmes-classiques/dijkstra/dijkstra2
      - file: content/ens/theme/algo1/activ/algorithmes-classiques/puissance4/puissance4
      - file: content/ens/theme/algo1/activ/formulation-solutions/maitre
      - file: content/ens/theme/algo1/consequences-automatisation/maitre

  - file: content/ens/theme/archi/main
    sections:
      - file: content/ens/theme/archi/activites
        sections:
        - file: content/ens/theme/archi/ordinateurantique
#    sections:
#      - file: content/ens/theme/archi/systemes-logiques/maitre
#      - file: content/ens/theme/archi/microprocesseur/maitre
#      - file: content/ens/theme/archi/elements-base-ordinateurs/maitre
#      - file: content/ens/theme/archi/architecture-von-neumann/maitre
#      - file: content/ens/theme/archi/informatique-embarquee/maitre
#      - file: content/ens/theme/archi/histoire-informatique/maitre

### Histoire de l'informatique  
- caption: Histoire
  chapters:
  - file: content/ens/theme/hist/main.md
    sections:
      - file: content/ens/theme/hist/jeuimitation.md
      - file: content/ens/theme/hist/smaky.md
  - file: content/ens/theme/hist/eval.md    
    sections:
      - file: content/ens/theme/hist/eval1.md


- caption: Enjeux sociaux
  numbered: false
  chapters:
  - file: content/ens/theme/enjeux/intro-enjeux
  - file: content/ens/theme/enjeux/grandes-thematiques/grandes-thematiques
    sections:
    - file: content/ens/theme/enjeux/grandes-thematiques/economie-numerique/economie-numerique
    - file: content/ens/theme/enjeux/grandes-thematiques/surveillance/surveillance
  - file: content/ens/theme/enjeux/fiches-complementaires/fiches-complementaires
    sections:
    - file: content/ens/theme/enjeux/fiches-complementaires/digital-labor/digital-labor
    - file: content/ens/theme/enjeux/fiches-complementaires/wikipedia/wikipedia
    - file: content/ens/theme/enjeux/fiches-complementaires/affaire-snowden/affaire-snowden
    - file: content/ens/theme/enjeux/fiches-complementaires/genre-numerique/genre-numerique
  - file: content/ens/theme/enjeux/bibliographie

## Annexes
- caption: Annexes
  numbered: false
  chapters: 
  - file: content/ens/playground/maitre
    sections:
      - file: content/ens/playground/notebook
      - file: content/ens/playground/types

## README
- caption: README
  numbered: false
  chapters:
  - file: content/ens/readme/0_presentation-ressources
    sections: 
      - file: content/ens/readme/exempleutilisation
      - file: content/ens/readme/modificationsressources
      - file: content/ens/readme/participation-developpement
      - file: content/ens/readme/syntaxemyst
      - file: content/ens/readme/extensions
      - file: content/ens/readme/glossaire
      - file: content/ens/readme/relectures
      - file: content/ens/readme/redaction-bonnes-pratiques

