name: deploy-book

# Only run this when the master branch changes
on: 
  push:
    branches: 
      - dev

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book-appr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      working-directory: .
    # Build the book
    - name: Build the book
      run: |
        sphinx-build src/appr build -E
      working-directory: .
    # Push the book's HTML to Infomaniak FTP
    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0-beta
      with:
        server: 31826.ftp.infomaniak.com
        username: 31826_elliot
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./build/
        server-dir: sites/dev-apprendre.modulo-info.ch/

  deploy-book-ens:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      working-directory: .
    # Build the book
    - name: Build the book
      run: |
        sphinx-build src/ens build -E
      working-directory: .
    # Push the book's HTML to Infomaniak FTP
    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0-beta
      with:
        server: 31826.ftp.infomaniak.com
        username: 31826_elliot
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./build/
        server-dir: sites/dev-enseigner.modulo-info.ch/
